token: "YOUR_SLACK_TOKEN"
blacklist: ["remember"] # The blacklist contains the plugins you don't want to use. The help plugin is always active
# whitelist: ["weather"] # The whitelist contains the plugins you only want to use. The help plugin is always active
weather:
  api_token: "GET THIS FROM http://openweathermap.org"
  default_city: "Melbourne,au"
randomtumblr:
  devops:
    name: DevOps Reactions
    url: "http://devopsreactions.tumblr.com"
    imagesrc: ".item img"
    titlesrc: ".post_title"
  infosec:
    name: Security Reactions
    url: "http://securityreactions.tumblr.com"
    imagesrc: "#posts .body-text img"
    titlesrc: "#posts .post-content .title"
  paintings:
    name: Classic Programmer Paintings
    url: "http://classicprogrammerpaintings.tumblr.com"
    imagesrc: "#posts .photo-wrapper-inner a img"
    titlesrc: "#posts .post-content figcaption"
  gosling:
    name: Programmer Ryan Gossling
    url: "http://programmerryangosling.tumblr.com"
    imagesrc: "#main article div img"
    titlesrc: ""
  onejob:
    name: You Had One Job
    url: "http://youhadonejob.org"
    titlesrc: "div.caption p"
    imagesrc: "#container .typePhoto img"
status:
  main: [aws, github, bitbucket, docker, npmjs]
remember:
  dynamodb: igorRemember
  admins:
    - arjen
